language: java

jdk:
- oraclejdk8

env:
  global:
  - secure: QgXFS+/DWjCRlHOFmpOZfNgdsojA1cC7whW6C/w4zlaOnxJUAIjRB2dzABr3lkl8me2/DsmdgEr21dokOaRpYRKgNKHZr0Bd6nJgX41vD1jIEMlFjnocKZrexNfd16aD7leAPg776MPoOvLvIICafSYyOO4uWBam3yFCAPd1Ei8cQOqsxp0njMqDDMPHYPzLut5aA7/iomDPXcptnJTNObjzus5f9HaS3JsCo+PgkSbuLz1kZ7zOB25jiBLM7PiuH5kTcsCBmxB6KCBi1gAsHD+Ret9/JxEQMPZDqi1A5DOCGPZmZhvHOQNYJp4OiGEzXSAIiiHBTwGY8zlKHtt55Af86FwJ8yXc+hM5/XW3w+KanN0r9x4ZT616hpiLH1iQbX26Ys0C5tS/vUHxdl6kFP06lxbchwJDyUjxWIGFwpq0zveK+BOJp9A4OjlJRNdA1ltrQ6tNIW/lukuAP8CwHnQDwFs3s5jCZPlIYT33HWILFUA6MCIqjFyAPmWmxF3RYq9PAHc2zlpTs7vmWPjp2iv2vH4b0lC2MIQyboRJOFSC0n3pwi8NNakpAzLgqUkXL+2QA61HHD59r8y8xrEY0WDrRIxPNoHBGKX0HjgNTfZWYdsKrglCJ0ufnX1LGONPfLVk3i/f8azNwf0dpI4gPgoSO88FpNAvBOKAiC4mbRo=

deploy:
  provider: releases
  api_key:
    secure: nW5xISpdDChUH9KTmVQII9slbb6YTG/ZjAaFdgJ3noknXITYYfP8qtm6hqTLtln/etGB5OkmKZNeVG6FM2QBhXID4L8U0uQzPsP2NGPMp3O18VtxiCiq+mxxCN5IFxqcCIqwOpaff7+moPcd3MYvvVQk/W0+ErW6hxu74JS2RkwNHKUPB2RMfeFr5knBmpuJwqgt9iUNKbuhnu5XPG5XkDVZxpm9RbRtLpR1p/lLt/vOC3MccNe/z4AzUc/Ks5shpfHUCsbebTUcKPMMRqsvaT6YwHfATi9d0tJnxlq/+OJV3A5ovMh4fYCousSvtlEUlGtRv7KHZKrUZ1lhOqOk0olMZiKQdcyFhusxT2dNyPz1WIM2hi34FOIgOFwpYpLeuUu5lzV7WtEuHdDrYNuqW8VP0DFdrQ5UXd5FPR4o9kqvoxcNLLLF0nh3Oqxh7UVxO44wX5SSylC92PlYtuR2qtzhB8zvu3Rlivxd8tiJ3Cb4RrumLq1yAJX64aN3DXqEtxF1rhtGLckAwtav3MTEhIVufItiKt3UzNNewWWgYhxebVdOTVnuvZhGmaXF77Gl2y8KUBjFKS+Bco0bZHHCqmkQ6LXpy88qlubmLBcJqv/DzZDyQlUwtOo17g9k4mRqaneP/Oxui2QLFPC8n9RrD8oBI6Bj2DgNYHzISZjBsTY=
  file:
    - build/libs/ImageBundler.jar
  skip_cleanup: true
  on:
    tags: true
